site_name: 网站title
site_url: https://setsuodu.github.io/WeatherAPI/
nav: # 定义网站左侧导航栏的结构
    - Home: index.md
    - 概念: concepts/intro.md
    - API 文档: api-docs.md        # 自动生成的路径

theme:
    name: material # 使用 MkDocs-Material 主题
    # ... 其他主题配置，如颜色、字体等

plugins:
    # 启用搜索功能
    - search
    # 如果要处理 Obsidian 链接和特性，需要在这里添加相应插件
    # - mkdocs-for-obsidian
    # - awesome-pages
    - swagger-ui-tag
      
markdown_extensions:
  - pymdownx.superfences      # 必须加这一行！！！
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
